### ISSUE TITLE
Using of Double for Sum-related values

### ISSUE THREAD

**Issue by Hixon10** [forgemo/bittrex-java-client#2]
Hi. 

You have code like that:
```
    private Double bid;
    private Double ask;
    private Double last;
```

It has errors:
https://en.wikipedia.org/wiki/Floating-point_arithmetic
https://en.wikipedia.org/wiki/Machine_epsilon

It is easy to fix this to migrate to **BigDecimal**, like that:
```
private BigDecimal bid;
private BigDecimal ask;
private BigDecimal last;
```

**Comment by forgemo** [comment]
Thanks for the info, I will look into it as soon as possible.

**Comment by forgemo** [comment]
done 282115dc7b3b62e1b7acba465ef9a5bc176a6f20

**Comment by Hixon10** [comment]
Thanks a lot!
