### ISSUE TITLE
Publish maven artifact

### ISSUE THREAD

**Issue by pgreze** [forgemo/bittrex-java-client#3]
Nice work with this library, I think next step would be to publish maven artifact somewhere (and avoid to clone/compile this project every time).

I don't know how to upload artifacts on MavenCentral/JCenter but jitpack.io can be used for easily distribute OSS: https://jitpack.io/#forgemo/bittrex-java-client/v2.0

Allowing to have a nice Gradle support as well:

```groovy
repositories {
    maven { url 'https://jitpack.io' }
}

dependencies {
    compile 'com.github.forgemo:bittrex-java-client:v2.0'
}
```

Could be nice to offer this solution in README as a first distribution channel.

**Comment by forgemo** [comment]
Thanks for your suggestions @pgreze . 

Publishing to MavenCentral requires a little bit too much effort for my taste (e.g. managing PGP keys). 

JitPack, however, is a good idea if you are willing to sacrifice some security for convenience. I updated the readme accordingly.
